name: coding_check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  pep8_check:
    # https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: apt-get update
      run: sudo apt-get update
    - name: install dependencies for PEP 8 code style check (ubuntu packages)
      run: sudo apt-get install pep8 pylint3
    - name: check PEP 8 code style
      run: pep8 --show-source --show-pep8 --statistics $(find -name "*.py")
    - name: run pylint
      run: pylint -j 3 --include-naming-hint=y --good-names=i,j,k,fd $(find -name "*.py")

  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      # https://github.com/marketplace/actions/checkout
    - uses: actions/setup-python@v2
      # https://github.com/marketplace/actions/setup-python
    - uses: pre-commit/action@v2.0.3
      # https://github.com/pre-commit/action
